name: Build & Deploy Vite App

on:
  push:
    branches:
      - main  # 또는 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: dist/
          remote_path: ~/team-dragon/nginx/html/
          remote_host: sanarae.duckdns.org
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}